import './globals.css'
import Scroll from './components/Scroll'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
  return (
    <html lang='fr'>
      <body>
        {/* <Header /> */}
        <main>{children}</main>
        <Scroll />

        <footer>{/* Votre pied de page */}</footer>
      </body>
    </html>
  )
}
